<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Default Rule</name>
  <uuid>5e4aeb3d-5dbf-44a4-b2ae-cafea1faf942</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to "No" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
