<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Calculate Ticket Age</name>
  <uuid>d8320332-1f7b-4b88-8439-27222ccc8d09</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the period between	'Ticket Date' and 'Current Date' ;
print "Ticket Age= "+ decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
