<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Escalate to Director</name>
  <uuid>4f63950e-9599-493c-93d1-6e1046196663</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	Escalate 
	and 'Affected System' is Payment System 
then
	set decision to Director ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
