<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Escalate To GM</name>
  <uuid>3d98e931-aa02-4506-9eac-772ba0ec57ba</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	Escalate is true 
	and 'Affected System' is Customer Care 
then
	set decision to General Manager ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
