<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>No Escalation</name>
  <uuid>3b4d754b-eb30-4de7-9393-7ed8cbdb64df</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	Escalate is false 
then
	set decision to None ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
