<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Existing Temp Limit more than 1000</name>
  <uuid>1c3f9f2c-654e-4eda-857c-05b144d49516</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'Existing Temp Limit Info' is more than 1000
then
	set decision to Decline ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
