<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Is Safe Balance</name>
  <uuid>7219e60a-fb71-41bd-b037-ac7a0e341040</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'Safe Balance' is false 
then
	set decision to Decline ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
