<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Membership more than 6 months</name>
  <uuid>987313df-90ff-4dee-b6d4-d929b1f1367c</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'Member more than 6 months' is "No" 
then
	set decision to Refer ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
