<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>LowPriority</name>
  <uuid>ffca6785-3423-43a3-bd77-347bfc2e5f96</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if Priority is Low then 
	set decision to "Ticket " + TicketID + " will be resolved in 8 hour";]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
