<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Customer Care rule</name>
  <uuid>f99ee956-b499-4790-9a86-a99aadc0b439</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if Severity is 1 and 'Affected System' is Customer Care then set decision to true ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
