<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Severity and Priority Rule</name>
  <uuid>b3d19552-8810-4423-8b01-a75310c32258</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	Priority is High 
	and Severity is 1 
then
	set decision to true ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
