<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Safe Balance</name>
  <uuid>2ea6c95d-09d3-4f25-a931-651bddd2d5b5</uuid>
  <documentation><![CDATA[Checks if the balance exceeds 10% the credit Limit]]></documentation>
  <locale>en_US</locale>
  <definition><![CDATA[// if the balance exceeds 10% more than the limit, this is not a safe balance
if
	the creditLimit of 'Bureau Info' * 1.1 - the accountBalance of 'Bureau Info' is less than 0 
then
	set decision to false ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
