<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>6fd910ed-c669-49af-8a28-6779482ba00e</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to No Change ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
