<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>HighPriority</name>
  <uuid>684c8cf1-4cb5-46bc-9553-b258336feba0</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if Priority is High then 
	set decision to "Ticket " + TicketID + " will be resolved LESS THANK 30 minutes";]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
