<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>MediumPriority</name>
  <uuid>88e198f4-30ef-4411-b66d-0be1362308a0</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if Priority is Medium then 
	set decision to "Ticket " + TicketID + " will be resolved in 4 hour";]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
