<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>life time value</name>
  <uuid>b2d0e701-2cd0-46d5-9ebb-e4b97ed11b6e</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the predicted ltv of 'ML model invocation' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
