<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Customer satisfaction questionnaire</name>
  <uuid>e7cd6fd3-f795-4a8d-bdaa-d24051502fc6</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    'Churn prediction'
then
    set the message of decision to "Send " + the name + " a customer satisfaction survey." ;
    set the estimated cost of decision to 0; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
