<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Discount for low ops cost</name>
  <uuid>86e3248c-0444-4b8f-ad6f-35df842893ad</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    'Churn prediction' and 'Low operation cost'
then
    set the message of decision to "Offer " + the name + " a 10% discount on his current subscription";
    set the estimated cost of decision to 0.1 * the usage; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
