<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>93c5ec16-018d-45c9-918b-31927512781f</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new recommendation where
        the estimated cost is 0, 
        the message is "No offer for this customer" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
