<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>VIP Discounted Upgrade</name>
  <uuid>b0b1f2ba-6ec9-477f-94e4-2ff52853515e</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    'Churn prediction'
    and 'VIP customer'
    and 'Logical upgrade' is not "KEEP OFFER"
then
    set the message of decision to "Upgrade " + the name + " to " + 'Logical upgrade' + " with a 20% discount, because he is an important customer.";
    set the estimated cost of decision to 0.2 * the usage; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
