<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Escalation Rule</name>
  <uuid>5d1211ca-e35b-40ee-b6ff-16b870caed2b</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	Severity is 1 
	and Priority is High 
	and 'Ticket Age' is longer than 4 hours 
then
	set decision to true;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
