<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>df385c3b-3c81-4bde-a562-3479c1db8055</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to "KEEP OFFER" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
